### ISSUE TITLE
Create hexagon logo

### ISSUE THREAD

**Issue by robbiedhickey** [nodeschool/fort-worth#1]
It's time to create a hexagon logo for the Forth Worth chapter! For inspiration/guidance there are plenty of examples here: https://nodeschool.io/hexdex.html  

Also, the svg template can be found here: https://github.com/nodeschool/nodeschool.github.io/blob/master/images/make-a-sticker/nodeschool-sticker-guide.svg 

If you've never messed with SVG, I've had some positive experience with Boxy SVG, which is a chrome app for vector graphics. It should be robust enough for tweaking the base template. 

Any thoughts on what color scheme or theme/imagery would be appropriate for Fort Worth? Some ideas:

- Montgomery Plaza
- Pioneer Tower
- Longhorn silhouette 
- Stockyards/Pawnee Bill 
- Trinity River/Trails
- Bicycling 
- Tarantula train
- Ten-gallon hat?

Running out of steam 😅

**Comment by megleighc** [comment]
Woohoo! Let's get this party started :)

**Comment by megleighc** [comment]
Logo created, not sure where to upload the .svg file or if I can upload it as our picture
