### ISSUE TITLE
'Javascripting' Workshopper Attendance

### ISSUE THREAD

**Issue by BeneventoFrank** [nodeschool/fort-worth#14]
7-26-2017 - our first meetup.

**Comment by BeneventoFrank** [comment]
@givingforwardmegan @hodorswit Where do you want this link on the site?

**Comment by BeneventoFrank** [comment]
I AM HERE!!!

**Comment by KenichiCarter** [comment]
Ken and Montree are here! :)

**Comment by mikengu** [comment]
Mike Ngu

Here :)
