### ISSUE TITLE
Create homepage 

### ISSUE THREAD

**Issue by robbiedhickey** [nodeschool/fort-worth#2]
We also need a landing page to post information about upcoming events and perhaps also to catalog past events. 

It would be nice to use one of the many static-site generators out there so adding content is straight-forward. Jekyll is probably the most popular and has a TON of templates for us to choose from. Gatsby also looks pretty interesting if we want to tinker with some React ✨🎉

**Comment by givingforwardmegan** [comment]
@hodorswit  I need permission to access the "Settings" option in our repository to use Jekyll. I have not looked at Gatsby yet.

**Comment by megleighc** [comment]
@BeneventoFrank  @hodorswit Will start on this during the week and weekend.

**Comment by robbiedhickey** [comment]
Great! Feel free to disregard the Jekyll/Gatsby suggestions made earlier. Let's just get some static markup and content out there.

**Comment by megleighc** [comment]
@hodorswit @BeneventoFrank I need some ideas on what our general "Overview" of Node is going to be (i.e. describing what it is, what we do, etc.).

**Comment by BeneventoFrank** [comment]
I'd say we should get some basic details out there similar to the other chapters.  

for the most part they just have a small mention of what nodeschool is and then just a section after that with our first meetup date.

**Comment by megleighc** [comment]
@hodorswit @BeneventoFrank Here is the link for our site at the moment, nodeschoolftw.carrd.co
I will get the files to you shortly.

**Comment by megleighc** [comment]
FYI I fixed the logo

**Comment by megleighc** [comment]
@hodorswit @BeneventoFrank Files for website made with Carrd template:
[Node School Fort Worth_CarrdSite.zip](https://github.com/nodeschool/fort-worth/files/1064878/Node.School.Fort.Worth_CarrdSite.zip)

**Comment by megleighc** [comment]
First homepage created.
