### ISSUE TITLE
Fix Hex Logo Spacing and Font by Exporting as Image

### ISSUE THREAD

**Issue by megleighc** [nodeschool/fort-worth#6]

**Comment by megleighc** [comment]
![node logo](https://cloud.githubusercontent.com/assets/14061367/23730585/daf5de9a-042d-11e7-9dd1-e1426a47d957.png)


@hodorswit  Updated logo as .png file attached - spacing and font should be corrected. Also decreased size of viewport logo is in.

**Comment by megleighc** [comment]
@hodorswit can we get this corrected logo pushed to replace our current one?

**Comment by robbiedhickey** [comment]
@givingforwardmegan looks like this png version of the logo does not have a transparent background. Can you attach a transparent version and I'll get it updated 

![image](https://cloud.githubusercontent.com/assets/349682/26465587/6c1f3a8c-4151-11e7-878d-dc923a9ce5a8.png)

**Comment by megleighc** [comment]
@hodorswit  Woops! Yes, I will get that done.

**Comment by givingforwardmegan** [comment]
![tnodelogo](https://cloud.githubusercontent.com/assets/14061367/26517045/64ca78ea-4256-11e7-8b31-a9b7e931ef81.png)

Logo background has been made transparent.

**Comment by megleighc** [comment]
![mainlogo](https://cloud.githubusercontent.com/assets/14061367/26521484/e370c02a-42ae-11e7-9d1d-a445d6baa2e9.png)

@hodorswit @BeneventoFrank Attached updated logo with transparent background.
Was having some trouble with the file on the Carrd templates and had to re-do it.
