### ISSUE TITLE
First FTW Node Meetup

### ISSUE THREAD

**Issue by megleighc** [nodeschool/fort-worth#8]
Please leave a comment below if you will be joining our first meetup.  If you will be bringing a guest, please note that in your comment so we are able to plan accordingly.

Thank you!
Megan

**Comment by thisbenrogers** [comment]
Sounds fun, planning on being there!

**Comment by Nooralwachi** [comment]
I want to join :)

**Comment by BeneventoFrank** [comment]
Closing - ALL RSVP should come through the Meetups site now so we can easily plan. Please click [HERE](http://meetu.ps/3bBv60) to RSVP.
